# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S_P68wyaYizjSh1-DpDpa4vyDhFAdT0Q
"""

# راح نستدعي مكتبات
import cv2
import urllib.request
from google.colab.patches import cv2_imshow





# تحميل ملف الجاهز للتعرف على الوجوه من النت
url = "https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/haarcascade_frontalface_default.xml"
urllib.request.urlretrieve(url, "haarcascade.xml")
# تفعيل خوارزمية التعرف على الوجوه
face_cascade = cv2.CascadeClassifier("haarcascade.xml")
# قائمة فيها أسماء الصور الثلاث
images = ["test1.jpg", "test2.jpg", "test3.jpg"]
# لوب على كل صوره يفحصها يعني تشوف فيها وجه أو لا
for name in images:
    img = cv2.imread(name)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # راح يحول الصورة للون الرمادي لتسريع الفحص
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.2, minNeighbors=12)

    # راح يرسم مربع أخضر حول كل وجه يتم اكتشافه
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)

    # ذا السطر يصغر حجم الصور يخليها زي بعض حجمها تقريبا
    resized_img = cv2.resize(img, (250, 250))





    # طباعة التفاصيل اسم الصورة وعدد الوجوه
    print("اسم الصورة:", name)
    print("عدد الوجوه المكتشفة:", len(faces))
    # فحص هل توجد وجوه في الصورة أم لا وطباعة النتيجة
    if len(faces) > 0:
        print("النتيجة: تم العثور على وجوه في هذه الصورة ✅")
    else:
        print("النتيجة: لا توجد وجوه في هذه الصورة ❌")




    # عرض الصورة لجميع الحالات (خارج الـ else)
    cv2_imshow(resized_img)
    print("-" * 30)
